language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - master
    - dev
before_script:
  - npm install -g @angular/cli
cache:
  directories:
    - ./node_modules
script:
  - ng lint
  - ng build --prod
  - ng test
