language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
branches:
  only:
    - master
    - dev
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
cache:
  directories:
    - ./node_modules
script:
  - ng build --prod
  - ng test

after_success:
  - ./deploy-command.sh
